spring:
  application:
    name: friendsnet
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
    url: jdbc:h2:~/db_friendsnet2;DB_CLOSE_DELAY=1000;AUTO_SERVER=TRUE
    username: a
    password: a
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
   org.springframework: INFO
   org.hibernate: INFO
server:
  port: 8080
